[package]
name = "mlutil-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "mlutil_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.4", features = ["extension-module"] }
# polars = { git = "https://github.com/pola-rs/polars":
